  version: 0.2

  phases:
    install:
      runtime-versions:
        python: 3.9
      commands:
        - echo "Installing Julia..."
        - wget -q https://julialang-s3.julialang.org/bin/linux/x64/1.9/
  julia-1.9.4-linux-x86_64.tar.gz
        - tar zxf julia-1.9.4-linux-x86_64.tar.gz
        - export PATH="$PWD/julia-1.9.4/bin:$PATH"
        - julia --version

    build:
      commands:
        - echo "Running Julia test for Tres Haciendas"
        - julia -e "println(\"Tres Haciendas Julia Test\")"
        - julia -e "vol = sqrt(252) * std(randn(100) * 0.02);
  println(\"Volatility: \", vol)"
        - echo "Julia test completed successfully"
